name: Keymap Drawer

on:
  push:
    paths:
      - 'keymap-drawer/keymap.yml'

jobs:
  draw-keymap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install keymap-drawer
      run: |
        python -m pip install --upgrade pip
        pip install keymap-drawer

    - name: Run keymap-drawer
      run: |
        keymap draw keymap-drawer/keymap.yml > keymap.svg

    - name: Upload SVG as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: keymap-svg
        path: keymap.svg
